# Generated by Django 4.1.7 on 2023-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='descr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classsection',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classsection',
            name='subject_descr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
