# Generated by Django 4.1.7 on 2023-04-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_classsection_descr_classsection_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='section_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
