# Generated by Django 4.1.7 on 2023-04-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_shoppingcart_student_shopping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_approved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
