# Generated by Django 4.1.7 on 2023-04-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_schedule_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_sent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_viewed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
